// ─── PC Component Seed Data ─────────────────────────────────────────────────
// This file contains a comprehensive catalog of PC components with
// compatibility fields used by the build generator service.

const components = [
  // ── CPUs ──────────────────────────────────────────────────────────────────
  {
    name: 'Intel Core i5-12400F',
    type: 'CPU',
    price: 174,
    wattage: 65,
    performanceScore: 55,
    socket: 'LGA1700',
    model_path: '/models/cpu.glb',
  },
  {
    name: 'Intel Core i7-13700K',
    type: 'CPU',
    price: 384,
    wattage: 125,
    performanceScore: 78,
    socket: 'LGA1700',
    model_path: '/models/cpu.glb',
  },
  {
    name: 'Intel Core i9-14900K',
    type: 'CPU',
    price: 549,
    wattage: 150,
    performanceScore: 95,
    socket: 'LGA1700',
    model_path: '/models/cpu.glb',
  },
  {
    name: 'AMD Ryzen 5 5600X',
    type: 'CPU',
    price: 199,
    wattage: 65,
    performanceScore: 58,
    socket: 'AM4',
    model_path: '/models/cpu.glb',
  },
  {
    name: 'AMD Ryzen 7 7700X',
    type: 'CPU',
    price: 349,
    wattage: 105,
    performanceScore: 75,
    socket: 'AM5',
    model_path: '/models/cpu.glb',
  },
  {
    name: 'AMD Ryzen 9 7950X',
    type: 'CPU',
    price: 574,
    wattage: 170,
    performanceScore: 96,
    socket: 'AM5',
    model_path: '/models/cpu.glb',
  },

  // ── GPUs ──────────────────────────────────────────────────────────────────
  {
    name: 'NVIDIA RTX 3060',
    type: 'GPU',
    price: 289,
    wattage: 170,
    performanceScore: 68,
    lengthMm: 242,
    model_path: '/models/gpu.glb',
  },
  {
    name: 'NVIDIA RTX 4070',
    type: 'GPU',
    price: 549,
    wattage: 200,
    performanceScore: 82,
    lengthMm: 285,
    model_path: '/models/gpu.glb',
  },
  {
    name: 'NVIDIA RTX 4080 Super',
    type: 'GPU',
    price: 999,
    wattage: 320,
    performanceScore: 92,
    lengthMm: 304,
    model_path: '/models/gpu.glb',
  },
  {
    name: 'AMD RX 7600',
    type: 'GPU',
    price: 249,
    wattage: 165,
    performanceScore: 62,
    lengthMm: 230,
    model_path: '/models/gpu.glb',
  },
  {
    name: 'AMD RX 7900 XT',
    type: 'GPU',
    price: 749,
    wattage: 300,
    performanceScore: 88,
    lengthMm: 276,
    model_path: '/models/gpu.glb',
  },
  {
    name: 'NVIDIA RTX 4090',
    type: 'GPU',
    price: 1599,
    wattage: 450,
    performanceScore: 99,
    lengthMm: 336,
    model_path: '/models/gpu.glb',
  },

  // ── RAM ───────────────────────────────────────────────────────────────────
  {
    name: 'Corsair Vengeance 16GB DDR4',
    type: 'RAM',
    price: 52,
    wattage: 5,
    performanceScore: 40,
    ramType: 'DDR4',
    capacityGB: 16,
    model_path: '/models/ram.glb',
  },
  {
    name: 'G.Skill Ripjaws 32GB DDR4',
    type: 'RAM',
    price: 89,
    wattage: 8,
    performanceScore: 55,
    ramType: 'DDR4',
    capacityGB: 32,
    model_path: '/models/ram.glb',
  },
  {
    name: 'Corsair Dominator 32GB DDR5',
    type: 'RAM',
    price: 139,
    wattage: 8,
    performanceScore: 70,
    ramType: 'DDR5',
    capacityGB: 32,
    model_path: '/models/ram.glb',
  },
  {
    name: 'G.Skill Trident Z5 64GB DDR5',
    type: 'RAM',
    price: 229,
    wattage: 12,
    performanceScore: 88,
    ramType: 'DDR5',
    capacityGB: 64,
    model_path: '/models/ram.glb',
  },

  // ── Motherboards ──────────────────────────────────────────────────────────
  {
    name: 'MSI PRO B660M-A',
    type: 'Motherboard',
    price: 119,
    wattage: 30,
    performanceScore: 45,
    socket: 'LGA1700',
    ramType: 'DDR4',
    formFactor: 'mATX',
    model_path: '/models/motherboard.glb',
  },
  {
    name: 'ASUS ROG Strix Z790-E',
    type: 'Motherboard',
    price: 379,
    wattage: 45,
    performanceScore: 80,
    socket: 'LGA1700',
    ramType: 'DDR5',
    formFactor: 'ATX',
    model_path: '/models/motherboard.glb',
  },
  {
    name: 'Gigabyte B550 AORUS Pro',
    type: 'Motherboard',
    price: 159,
    wattage: 35,
    performanceScore: 55,
    socket: 'AM4',
    ramType: 'DDR4',
    formFactor: 'ATX',
    model_path: '/models/motherboard.glb',
  },
  {
    name: 'MSI MAG X670E TOMAHAWK',
    type: 'Motherboard',
    price: 289,
    wattage: 40,
    performanceScore: 72,
    socket: 'AM5',
    ramType: 'DDR5',
    formFactor: 'ATX',
    model_path: '/models/motherboard.glb',
  },

  // ── Storage ───────────────────────────────────────────────────────────────
  {
    name: 'Samsung 870 EVO 500GB SATA',
    type: 'Storage',
    price: 49,
    wattage: 4,
    performanceScore: 35,
    capacityGB: 500,
    storageType: 'SATA SSD',
    model_path: '/models/storage.glb',
  },
  {
    name: 'Samsung 980 Pro 1TB NVMe',
    type: 'Storage',
    price: 109,
    wattage: 6,
    performanceScore: 70,
    capacityGB: 1000,
    storageType: 'NVMe',
    model_path: '/models/storage.glb',
  },
  {
    name: 'WD Black SN850X 2TB NVMe',
    type: 'Storage',
    price: 179,
    wattage: 7,
    performanceScore: 82,
    capacityGB: 2000,
    storageType: 'NVMe',
    model_path: '/models/storage.glb',
  },
  {
    name: 'Seagate Barracuda 2TB HDD',
    type: 'Storage',
    price: 54,
    wattage: 8,
    performanceScore: 20,
    capacityGB: 2000,
    storageType: 'HDD',
    model_path: '/models/storage.glb',
  },

  // ── PSUs ──────────────────────────────────────────────────────────────────
  {
    name: 'EVGA 500W Bronze',
    type: 'PSU',
    price: 49,
    wattage: 15,
    performanceScore: 30,
    capacityWatts: 500,
    efficiency: '80+ Bronze',
    model_path: '/models/psu.glb',
  },
  {
    name: 'Corsair RM650x Gold',
    type: 'PSU',
    price: 99,
    wattage: 18,
    performanceScore: 55,
    capacityWatts: 650,
    efficiency: '80+ Gold',
    model_path: '/models/psu.glb',
  },
  {
    name: 'Corsair RM850x Gold',
    type: 'PSU',
    price: 139,
    wattage: 22,
    performanceScore: 72,
    capacityWatts: 850,
    efficiency: '80+ Gold',
    model_path: '/models/psu.glb',
  },
  {
    name: 'Seasonic Prime TX-1000',
    type: 'PSU',
    price: 239,
    wattage: 25,
    performanceScore: 90,
    capacityWatts: 1000,
    efficiency: '80+ Titanium',
    model_path: '/models/psu.glb',
  },
  {
    name: 'Corsair HX1200 Platinum',
    type: 'PSU',
    price: 279,
    wattage: 28,
    performanceScore: 95,
    capacityWatts: 1200,
    efficiency: '80+ Platinum',
    model_path: '/models/psu.glb',
  },

  // ── Cases ─────────────────────────────────────────────────────────────────
  {
    name: 'NZXT H510',
    type: 'Case',
    price: 79,
    wattage: 0,
    performanceScore: 45,
    formFactor: 'ATX',
    maxGpuLengthMm: 325,
    model_path: '/models/case.glb',
  },
  {
    name: 'Corsair 4000D Airflow',
    type: 'Case',
    price: 104,
    wattage: 0,
    performanceScore: 65,
    formFactor: 'ATX',
    maxGpuLengthMm: 360,
    model_path: '/models/case.glb',
  },
  {
    name: 'Lian Li O11 Dynamic',
    type: 'Case',
    price: 149,
    wattage: 0,
    performanceScore: 80,
    formFactor: 'ATX',
    maxGpuLengthMm: 395,
    model_path: '/models/case.glb',
  },
  {
    name: 'Cooler Master NR200',
    type: 'Case',
    price: 89,
    wattage: 0,
    performanceScore: 50,
    formFactor: 'mATX',
    maxGpuLengthMm: 280,
    model_path: '/models/case.glb',
  },

  // ── Cooling ───────────────────────────────────────────────────────────────
  {
    name: 'Cooler Master Hyper 212',
    type: 'Cooling',
    price: 35,
    wattage: 5,
    performanceScore: 40,
    coolingType: 'Air',
    socketSupport: ['LGA1700', 'AM4', 'AM5'],
    model_path: '/models/cooling.glb',
  },
  {
    name: 'Noctua NH-D15',
    type: 'Cooling',
    price: 99,
    wattage: 8,
    performanceScore: 75,
    coolingType: 'Air',
    socketSupport: ['LGA1700', 'AM4', 'AM5'],
    model_path: '/models/cooling.glb',
  },
  {
    name: 'Corsair iCUE H150i Elite',
    type: 'Cooling',
    price: 169,
    wattage: 12,
    performanceScore: 85,
    coolingType: 'AIO Liquid 360mm',
    socketSupport: ['LGA1700', 'AM4', 'AM5'],
    model_path: '/models/cooling.glb',
  },
  {
    name: 'NZXT Kraken X63',
    type: 'Cooling',
    price: 139,
    wattage: 10,
    performanceScore: 78,
    coolingType: 'AIO Liquid 280mm',
    socketSupport: ['LGA1700', 'AM4', 'AM5'],
    model_path: '/models/cooling.glb',
  },
];

export default components;
